# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# script.py
# Created on: 2017-12-01 14:47:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
glut_lc_2008_img = "C:\\Users\\bpdura7983\\Desktop\\glut_lc_2008.img"
glut_lc_2008_img__2_ = glut_lc_2008_img

# Process: Build Raster Attribute Table
arcpy.BuildRasterAttributeTable_management(glut_lc_2008_img, "NONE")

# tool variables
in_table="Pixel Count "
out_csv_file="Pixel_Acres"
in_delimiter="COMMA"

# Local variables:
Output_Feature_Class__2_ = ""

glut_lc_2008_img__2_ = glut_lc_2008_img
table_dbf = "C:\\Users\\bpdura7983\\Desktop\\table.dbf"
table_dbf__2_ = table_dbf
table_dbf__3_ = table_dbf__2_
