# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# script.py
# Created on: 2017-12-01 14:47:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


